#!/usr/bin/env bash

# MATRIZ NEOLÓGICA - DEBUGGING GUIDE
# ===================================

echo "🔍 DEBUGGING MATRIX NEOLÓGICA V2.6"
echo ""
echo "Se está a ver apenas palavras do fallback (Global, Brasil, etc),"
echo "execute os passos abaixo para identificar o problema:"
echo ""

echo "📋 PASSO 1: Abra DevTools (F12)"
echo "   └─ Ctrl+Shift+I (Windows/Linux) ou Cmd+Option+I (Mac)"
echo ""

echo "📋 PASSO 2: Copie e execute este comando no Console:"
echo ""
echo "   window.testFetch()"
echo ""
echo "   Isso irá:"
echo "   ✓ Tentar buscar dados do Google Trends"
echo "   ✓ Mostrar qual proxy funcionou"
echo "   ✓ Listar os termos recebidos"
echo ""

echo "🎯 RESULTADOS ESPERADOS:"
echo ""
echo "SUCESSO (Vê termos com origem 'Google_Pulse_PT'):"
echo "   ✅ Google Trends: 25 termos carregados com sucesso!"
echo "   📝 Amostra: { termo: \"Eleição 2026\", origem: \"Google_Pulse_PT\", ... }"
echo ""
echo "FALHA (Vê mensagens de erro):"
echo "   ❌ Todos os proxies falharam"
echo "   → Significa que nenhum proxy CORS está disponível"
echo "   → Google Trends RSS pode estar temporariamente indisponível"
echo ""

echo "🔧 PRÓXIMAS AÇÕES SE FALHAR:"
echo ""
echo "1️⃣  Verificar Network Tab (F12 > Network):"
echo "    └─ Recarregue a página (Ctrl+R)"
echo "    └─ Procure por requisições para:"
echo "       • allorigins.win"
echo "       • cors-anywhere.herokuapp.com"
echo "       • thingproxy.freeboard.io"
echo ""
echo "    Se o status for 403/429 → Proxy está bloqueado"
echo "    Se tiver erro CORS → Problema de segurança"
echo ""

echo "2️⃣  Verifique o console pelo log completo:"
echo "    └─ Procure por: '🔄 Fetching Google Trends'"
echo "    └─ Veja qual proxy foi tentado"
echo "    └─ Procure por: '✅ Proxy X funcionou' ou '❌ Proxy X falhou'"
echo ""

echo "3️⃣  Se TUDO falhar:"
echo "    └─ Execute: window.reloadTrends()"
echo "    └─ Tente novamente após alguns segundos"
echo "    └─ Pode ser que a rede esteja lenta/temporariamente indisponível"
echo ""

echo "📊 VERIFICAR ESTADO ATUAL:"
echo ""
echo "   window.wordsDB          // Array com dados carregados"
echo "   window.isDataLoaded     // true se dados foram carregados"
echo "   window.mockData         // Array com fallback (10 termos)"
echo ""

echo "🆘 DIAGNÓSTICO RÁPIDO:"
echo ""
echo "1. Recarregue a página (Ctrl+F5)"
echo "2. Clique SINTONIZAR_MATRIZ"
echo "3. Aguarde 3-5 segundos"
echo "4. Abra F12 e procure por:"
echo "   - '✅ Google Trends' = SUCESSO (palavras reais)"
echo "   - '⚠️ Todos os provedores' = FALLBACK (palavras stock)"
echo "5. Execute window.testFetch() para forçar novo teste"
echo ""

echo "✅ FIM DO GUIA"
